### ISSUE TITLE
gDocs connector

### ISSUE THREAD

**Issue by duncdrum** [Juris-M/zotero#115]
As mentioned in [this thread](https://forums.zotero.org/discussion/87938/google-docs-zotero-wont-cite-just-pulls-up-link-function) Jurism can no longer talk to google docs. The fork of the connector hasn't enabled the issues feature, so i m posting his here. 

Tested with macOS `11.2.3` ,  `10.15.6` 
Browser FF, CHrome Safari (all the latest and greatest)
Jurism: `5.0.93m18`
FF- Jurism Connector: `5.0.93.4` (connects but cannot insert citation, citation picker comes)
Chrome Zotero Connector `5.0.83` (cannot connect to Jurism)

**Comment by fbennett** [comment]
Dear Duncan,

Thanks for the heads-up. I'll try to get a. Update out within a week. Sorry
for the delay, I've several things on my plate here locally.

Frank

**Comment by duncdrum** [comment]
Thank you Frank

**Comment by AndrewRens** [comment]
Probably the same issue:

Error: Using Juris-M in Google Docs:

Steps to recreate:

The steps are the same in Firefox or Chrome, the same error occurs in both

Open new Google Document
Select Juris-M
Select Add/Edit Citation
The dialogue box opens and one selects citation style
The add/edit citation box open -> select citation
select OK
A box pops up with:

"Zotero

Jurism experienced an error updating your document"

Error logs:

Firefox:
[JavaScript Error: "Localized string
'integration_googleDocs_orphanedCitations_buttonTooltip' not defined
getString@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/i18n.js:40:20
window.Zotero</this.getString@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/zotero.js:368:22
Zotero.GoogleDocs.UI.OrphanedCitations<@sandbox eval code:1027:28
we@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:84:293
nh@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:96:43
zj@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:230:425
Th@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:152:225
tj@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:152:152
Te@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:146:151
Ja@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:224:381
md@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:173:45
nd/<@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:175:224
Rh@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:147:64
nd@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:175:210
I.render@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:238:412
injectIntoDOM@sandbox eval code:106:16
init@sandbox eval code:61:12
" {file: "[object Object]"}]

[JavaScript Error: "Localized string
'integration_googleDocs_orphanedCitations_disclaimer' not defined
getString@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/i18n.js:40:20
window.Zotero</this.getString@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/zotero.js:368:22
Zotero.GoogleDocs.UI.OrphanedCitationsList@sandbox eval code:1090:24
we@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:84:293
zj@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:226:496
Th@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:152:225
tj@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:152:152
Te@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:146:151
Ja@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:224:381
md@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:173:45
nd/<@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:175:224
Rh@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:147:64
nd@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:175:210
I.render@moz-extension://b0c112a9-8675-44c8-b926-208d76303bc1/lib/react-dom.js:238:412
injectIntoDOM@sandbox eval code:106:16
init@sandbox eval code:61:12
" {file: "[object Object]"}]

[JavaScript Error: "urlInput is undefined
insertLink@sandbox eval code:587:7
" {file: "[object Object]"}]

connector => true, version => 5.0.93.4, platform => Linux x86_64,
locale => en-US, userAgent => Mozilla/5.0 (X11; Ubuntu; Linux x86_64;
rv:86.0) Gecko/20100101 Firefox/86.0, appName => Juris-M Connector for
Firefox, zoteroAvailable => true

Chrome:
JavaScript Error: "Error: Localized string
'integration_googleDocs_orphanedCitations_buttonTooltip' not defined
at Object.getString
(chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/i18n.js:40:20)
at Object.getString
(chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/zotero.js:368:22)
at :1027:28
at we (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:84:293)
at nh (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:96:43)
at zj (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:230:425)
at Th (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:152:223)
at tj (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:152:152)
at Te (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:146:151)
at chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:61:68"
{file: "[object Object]"}]

[JavaScript Error: "Error: Localized string
'integration_googleDocs_orphanedCitations_disclaimer' not defined
at Object.getString
(chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/i18n.js:40:20)
at Object.getString
(chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/zotero.js:368:22)
at Zotero.GoogleDocs.UI.OrphanedCitationsList (:1090:24)
at we (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:84:293)
at He (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:97:464)
at zj (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:228:406)
at Th (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:152:223)
at tj (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:152:152)
at Te (chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:146:151)
at chrome-extension://pbhldkcipcaeniadfnhhdaealdfjgbpj/lib/react-dom.js:61:68"
{file: "[object Object]"}]

[JavaScript Error: "TypeError: Cannot set property 'value' of undefined
at Object.insertLink (:587:22)
at async Zotero.GoogleDocs.Client._insertField (:333:3)
at async Zotero.GoogleDocs.Client.setDocumentData (:208:5)
at async Zotero.GoogleDocs.Client.call (:152:13)"
{file: "[object Object]"}]

connector => true, version => 5.0.93.4, platform => Linux x86_64,
locale => en-US, userAgent => Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72
Safari/537.36, appName => Juris-M Connector for Chrome,
zoteroAvailable => true, extensions => Docs (0.10,
legacy_packaged_app), Google Drive (14.5, hosted_app), YouTube (4.2.8,
hosted_app), Google Search (0.0.0.60, hosted_app), Google Docs Offline
(1.28.0, extension), Unpaywall (3.94, extension), Save to Pocket
(3.1.3.0, extension), Juris-M Connector (5.0.93.4, extension), Gmail
(8.3, hosted_app)

Client: (does not seem relevant)

[JavaScript Warning: "Failed to load overlay from
chrome://global/content/editMenuOverlay.xul." {file:
"chrome://global/content/console.xul" line: 0}]
[JavaScript Error: "Localized string not available for field
'committeeFullname'"]
[JavaScript Warning: "unreachable code after return statement" {file:
"resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js"
line: 201 column: 4 source: " eval(obj);
"}]

**Comment by rien** [comment]
There still seems to be an issue with this. Juris-M does not seem to be working with Google Docs anymore.
